# Welcome to Jekyll!

# Website settings
title: Saksham Sinha
description: Jack's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl:
url: http://www.sakshamsinha.github.io
# url: http://127.0.0.1:4000
img_path: /static/assets/img/blog

# author
author:
  name: Saksham
  first_name: Saksham
  last_name: Sinha
  cv: /static/cv/Saksham_Sinha_Resume.pdf
  email: ssinha@tcd.ie
  facebook_username: saksham.sinha
  github_username: SakshamSinha
  linkedin_id: sakshamsinha
  avatar: /static/assets/img/landing/Jack.jpeg
  skill_icon1:
    - name: icon-python
    - name: icon-c
  skill_icon2:
    - name: icon-cplusplus
    - name: icon-docker
  desc: Nothing for now
# comment
disqus:
  name: jalpc

# analytics
## google analytics
ga:
  id: UA-93473370-1

go:
  id: GTM-NHMS8GD

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: off

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
